development:
  database: library
  adapter: mysql2
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
  encoding: latin1

test:
  database: library_test
  adapter: mysql2
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
  encoding: latin1

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: root
  password:
